int bitAnd(int x, int y); 
int bitOr(int x, int y); 
int isEqual(int x, int y); 
int logicalShift(int x, int n); 
int bitParity(int x);
int leastBitPos(int x); 
int bitCount(int x); 
int bang(int x); 
int tmax(void); 
int negate(int x); 
int addOK(int x, int y); 
int isNonZero(int x);
int sm2tc(int x); 
int abs(int x); 
int satAdd(int x, int y); 

int test_bitAnd(int x, int y); 
int test_bitOr(int x, int y); 
int test_isEqual(int x, int y); 
int test_logicalShift(int x, int n); 
int test_bitParity(int x);
int test_leastBitPos(int x); 
int test_bitCount(int x); 
int test_bang(int x); 
int test_tmax(void); 
int test_negate(int x); 
int test_addOK(int x, int y); 
int test_isNonZero(int x);
int test_sm2tc(int x); 
int test_abs(int x); 
int test_satAdd(int x, int y);
